version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HelloWorld10"
    platform: linux/amd64
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local